#!/usr/bin/env bash

PORT_NUMBER="${1}"
PID="$(lsof -t -i:${PORT_NUMBER})" || echo "No process with port number ${PORT_NUMBER}"

if [[ "${PID}" ]]; then
  echo "killing PID ${PID}"
  kill -9 ${PID}
fi
